#!/bin/bash
#TospoVirus: Weaponizing vulnerabilities for fun and... just fun.
#Author: 
#   twitter @catatonicprime 
#   email (guess)
#
#n00b comments provided by:
#   ActualReverend


# this version a placeholder for rest of code later, after presentation
